---
- name: Build and Push Docker image on Master
  hosts: master
  tasks:
      # PlayBook 복사하기
    - name: Copy Ansible Playbook to Master
      copy:
        src: /var/lib/jenkins/workspace/subject_jenkins/playbook.yml  # Jenkins에서 뽑아올 경로
        dest: /root/jen/playbook.yml #복사해서 들어갈 경로
      # Deploy용 yml 복사하기
    - name: Copy Ansible Deploy to Master
      copy:
        src: /var/lib/jenkins/workspace/subject_jenkins/testpod.yml  # Jenkins에서 뽑아올 경로
        dest: /root/jen/testpod.yml #복사해서 들어갈 경로
  
    # - name: Log in to Docker Hub #이부분은 나중에 env로 해줘야함
    #   command: docker login -u pshhhhh98 -p a1a2a3a4@@

    - name: Log in to Docker Hub #이부분은 나중에 env로 해줘야함
      command: sudo docker login https://211.183.3.105 -u admin -p Harbor12345

    - name: Build Docker image  # 이미지 빌드하기
      command: docker build -t subject:harbor .
      args:
        chdir: /root/jen/subject_option  # Dockerfile이 있는 경로

    - name: Tag Harbor Docker image # 하버에 올라갈 이미지 태그하기
      command: docker tag subject:harbor  211.183.3.105/subject_harbor/subject:harbor 

    - name: Push Docker image to Docker Hub  # 이미지 푸시하기
      command: docker push 211.183.3.105/subject_harbor/subject:harbor 

    - name: Apply Deployment                                                            
      command: kubectl apply -f /root/jen/testpod.yml  # 직접 명령어로 배포하니까, 기존의 배포 pod의 멱등성이 깨짐, 따로 yml파일을 만들어서 apply하기