---
- name: Build and Push Docker image on Master
  hosts: master
  tasks:
    - name: Load Docker credentials from .env file
      ansible.builtin.set_fact:
        docker_env: "{{ lookup('file', '/home/user1/login.env') | from_yaml }}"

    - name: Log in to Docker Hub
      community.docker.docker_login:
        username: "{{ docker_env.DOCKER_USERNAME }}"
        password: "{{ docker_env.DOCKER_PASSWORD }}"
      no_log: true

    - name: Build Docker image
      ansible.builtin.command:
        cmd: docker build -t pshhhhh98/subject:jenkin .
      args:
        chdir: /root/jen  # Dockerfile이 위치한 디렉토리

    - name: Push Docker image to Docker Hub
      ansible.builtin.command:
        cmd: docker push pshhhhh98/subject:jenkin

    - name: Deploy to Kubernetes
      ansible.builtin.command:
        cmd: kubectl create deploy web-puple --replicas=3 --port=80 --image=pshhhhh98/subject:jenkin
      ignore_errors: yes  # 배포가 이미 존재하는 경우 오류 무시

    - name: Expose Service on Kubernetes
      ansible.builtin.command:
        cmd: kubectl expose deploy web-puple --type=LoadBalancer --port=80 --target-port=80 --name=web-puple-svc
      ignore_errors: yes  # 서비스가 이미 존재하는 경우 오류 무시
