---
- name: Build and Push Docker image on Master
  hosts: master
  tasks:
    - name: Copy Ansible Playbook to Master
      copy:
        src: /var/lib/jenkins/workspace/subject_jenkins/playbook.yml  # Jenkins에서 뽑아올 경로
        dest: /root/jen/playbook.yml #복사해서 들어갈 경로
  
    - name: Log in to Docker Hub #이부분은 나중에 env로 해줘야함
      command: docker login -u pshhhhh98 -p a1a2a3a4@@

    - name: Build Docker image
      command: docker build -t pshhhhh98/subject:jenkins .
      args:
        chdir: /root/jen/subject_option  # Dockerfile이 있는 경로

    - name: Push Docker image to Docker Hub
      command: docker push pshhhhh98/subject:jenkins


    # # pod 만들기
    # - name: Deploy to Kubernetes
    #   command: kubectl create deploy jenjen --replicas=2 --port=80 --image=pshhhhh98/subject:jenkins
    #   ignore_errors: yes  # 배포가 이미 존재하는 경우 오류 무시
    # # 로드밸런서 만들기 
    # - name: Expose Service on Kubernetes
    #   command: kubectl expose deploy jenjen --type=LoadBalancer --port=80 --target-port=80 --name=jenjen-svc
    #   ignore_errors: yes  # 서비스가 이미 존재하는 경우 오류 무시

    - name: Apply Deployment
      command: kubectl apply -f /var/lib/jenkins/workspace/subject_jenkins/testpod.yml  # 직접 명령어로 배포하니까, 기존의 배포 pod의 멱등성이 깨짐, 따로 yml파일을 만들어서 apply하기