---
- name: Build and Push Docker image on Master
  hosts: master
  tasks:
    - name: Log in to Docker Hub #이부분은 나중에 env로 해줘야함
      command: docker login -u pshhhhh98 -p a1a2a3a4@@

    - name: Build Docker image
      command: docker build -t pshhhhh98/keduitlab:yellow .
      args:
        chdir: /root/jen  # 마스터 노드의 Dockerfile이 위치한 디렉토리

    - name: Push Docker image to Docker Hub
      command: docker push pshhhhh98/keduitlab:yellow

    - name: Deploy to Kubernetes
      command: kubectl create deploy web-puple --replicas=3 --port=80 --image=pshhhhh98/keduitlab:yellow
      ignore_errors: yes  # 배포가 이미 존재하는 경우 오류 무시

    - name: Expose Service on Kubernetes
      command: kubectl expose deploy web-puple --type=LoadBalancer --port=80 --target-port=80 --name=web-puple-svc
      ignore_errors: yes  # 서비스가 이미 존재하는 경우 오류 무시
