---
- name: Build and Push Docker image on Master
  hosts: master
  tasks:
    - name: Load environment variables from .env file
      include_vars:
        file: /root/login.env  # .env 파일의 경로를 설정합니다.
        name: env_vars

    - name: Log in to Docker Hub
      command: docker login -u {{ env_vars.DOCKER_USERNAME }} -p {{ env_vars.DOCKER_PASSWORD }}
      no_log: true

    - name: Build Docker image
      command: docker build -t {{ env_vars.DOCKER_USERNAME }}/keduitlab:yellow .
      args:
        chdir: /root/jen  # 마스터 노드의 Dockerfile이 위치한 디렉토리

    - name: Push Docker image to Docker Hub
      command: docker push {{ env_vars.DOCKER_USERNAME }}/keduitlab:yellow

    - name: Deploy to Kubernetes
      command: kubectl create deploy web-puple --replicas=3 --port=80 --image={{ env_vars.DOCKER_USERNAME }}/keduitlab:yellow
      ignore_errors: yes  # 배포가 이미 존재하는 경우 오류 무시

    - name: Expose Service on Kubernetes
      command: kubectl expose deploy web-puple --type=LoadBalancer --port=80 --target-port=80 --name=web-puple-svc
      ignore_errors: yes  # 서비스가 이미 존재하는 경우 오류 무시

