---
- name: Build and Push Docker image on Master
  hosts: master
  tasks:
    - name: Log in to Docker Hub #이부분은 나중에 env로 해줘야함
      command: docker login -u pshhhhh98 -p a1a2a3a4@@

    - name: Build Docker image
      command: docker build -t pshhhhh98/subject:jenkins .
      args:
        chdir: /var/lib/jenkins/workspace/subject_jenkins  # Dockerfile이 있는 경로

    - name: Push Docker image to Docker Hub
      command: docker push pshhhhh98/subject:jenkins

    - name: Deploy to Kubernetes
      command: kubectl create deploy jenjen --replicas=3 --port=80 --image=pshhhhh98/subject:jenkins
      ignore_errors: yes  # 배포가 이미 존재하는 경우 오류 무시

    - name: Expose Service on Kubernetes
      command: kubectl expose deploy jenjen --type=LoadBalancer --port=80 --target-port=80 --name=jenjen-svc
      ignore_errors: yes  # 서비스가 이미 존재하는 경우 오류 무시
